In [14]:
import json

In [15]:
exp1_file = "/storage/brno2/home/rahmang/xcomet/arafat_comet/COMET_GR/Postedit_exp1.json"

In [16]:
# Load JSON data
with open(exp1_file, 'r', encoding='utf-8') as f:
    exp1_json = json.load(f)

In [17]:
exp1_data = exp1_json[2]["data"]

In [18]:
actual_data = []
for pe in exp1_data:
    # print(pe["finalised"])
    if pe["finalised"] == "1" and pe["user_id"] != "501":
        print("i am here")
        actual_data.append(pe)

i am here
i am here
i am here
i am here
i am here
i am here
i am here
i am here

In [19]:
len(actual_data)

8

In [20]:
import pandas as pd

# define the columns you want to keep
keep_columns = ['id', 'user_id', 'translation_id', 'annotator_id', 'text']

# convert to DataFrame and keep only those columns
df = pd.DataFrame(actual_data)[keep_columns]

In [21]:
print(df)

     id user_id translation_id annotator_id  \
0  4004     502          18608            1
1  4005     502           2433            1
2  4006     502            935            1
3  4007     502          18234            1
4  4008     503           2433            1
5  4009     503          18608            1
6  4010     503          18234            1
7  4011     503            935            1

                                                text
0  Exploration de la structure catégorielle à l'a...
1  Correction et validation des dépendances synta...
2  Efficacité des modèles de langue du français s...
3  Modèle sémantique basé sur BERT pour le rescor...
4  Correction et validation des dépendances synta...
5  Exploration de la structure des catégories à l...
6  Modèle sémantique basé sur BERT pour le rescor...
7  Efficacité des modèles de langue français pour...

In [1]:
from comet import download_model, load_from_checkpoint

model_path = download_model("Unbabel/XCOMET-XL")
#model = load_from_checkpoint(model_path)

/storage/brno2/home/rahmang/envs/xcomet/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Fetching 5 files: 100%|██████████| 5/5 [00:00<00:00, 4360.89it/s]

In [13]:
from comet import download_model, load_from_checkpoint
from comet.models.multitask.unified_metric import UnifiedMetric
class CustomXCOMET(UnifiedMetric):
    print("custom unified_metric")
    
# Load checkpoint into your custom class
#path = "/storage/brno2/home/rahmang/xcomet/downloadedxcomet/models--Unbabel--XCOMET-XL/snapshots/50d428488e021205a775d5fab7aacd9502b58e64/checkpoints/model.ckpt"

model = CustomXCOMET.load_from_checkpoint(model_path,strict = False)

custom unified_metric

Encoder model frozen.
/storage/brno2/home/rahmang/envs/xcomet/lib/python3.11/site-packages/pytorch_lightning/core/saving.py:195: Found keys that are not in the model state dict but in the checkpoint: ['encoder.model.embeddings.position_ids']

#### MTs

In [2]:
text18608 = """Exploration de la structure des catégories à l'aide de modèles linguistiques contextuels et de réseaux sémantiques lexicaux

Des travaux récents sur la prédiction de la structure des catégories avec des modèles distributionnels, utilisant soit des enchâssements de mots statiques (Heyman et Heyman, 2019), soit des modèles de langage contextualisés (CLM) (Misra et al., 2021), font état de faibles corrélations avec les évaluations humaines, remettant ainsi en question leur plausibilité en tant que modèles de la mémoire sémantique humaine. Dans ce travail, nous revisitons cette question en testant un plus large éventail de méthodes pour sonder les CLMs afin de prédire les scores de typicalité. Nos expériences, utilisant BERT (Devlin et al., 2018), montrent l'importance d'utiliser le bon type de sondes CLM, car nos meilleures méthodes de prédiction de typicalité basées sur BERT s'améliorent considérablement par rapport aux travaux précédents. Deuxièmement, nos résultats soulignent l'importance de la polysémie dans cette tâche : nos meilleurs résultats sont obtenus lors de l'utilisation d'un mécanisme de désambiguïsation. Enfin, des expériences supplémentaires révèlent que le WordNet basé sur le contenu de l'information (Miller, 1995), également doté d'un mécanisme de désambiguïsation, atteint les mêmes performances que la meilleure méthode basée sur l'ERTB et capture en fait des informations complémentaires, qui peuvent être combinées avec l'ERTB pour améliorer les prédictions de typicalité."""

In [3]:
text935 = """Efficacité des modèles de langue française sur la tâche de synthèse du dialogue abstrait

Les modèles linguistiques pré-formés ont établi l’état de l’art sur diverses tâches de traitement du langage naturel, y compris la synthèse du dialogue, qui permet au lecteur d’accéder rapidement aux informations clés provenant de longues conversations lors de réunions, d’entretiens ou d’appels téléphoniques. Cependant, de tels dialogues sont encore difficiles à gérer avec les modèles actuels car la spontanéité du langage implique des expressions rarement présentes dans les corpus utilisés pour la préformation des modèles linguistiques. En outre, la grande majorité du travail accompli dans ce domaine a été axée sur l’anglais. Dans ce travail, nous présentons une étude sur la synthèse des dialogues oraux spontanés en français en utilisant plusieurs modèles pré-formés spécifiques à la langue: Barthez, et BelGPT-2, ainsi que des modèles pré-formés multilingues: MBart, mBARThez et mT5. Des expériences ont été réalisées sur le corpus de dialogue DECODA (Call Center) dont la tâche est de générer des synopses abstraites à partir des conversations du centre d’appels entre un appelant et un ou plusieurs agents en fonction de la situation. Les résultats montrent que les modèles Barthez offrent les meilleures performances bien au-dessus de l’état de la technologie précédent sur DECODA. Nous discutons en outre des limites de ces modèles pré-formés et des défis à relever pour résumer les dialogues spontanés."""

In [4]:
text2433 = """Correction et validation de la dépendance syntaxique dans le Rhapsodie de la banque d’arbres française parlée

Cet article présente les méthodes, les résultats et la précision du processus d’annotation syntaxique de la Rhapsodie Treebank de français parlé. Le Rhapsodie Treebank est un corpus de 33 000 mots annoté pour la prosodie et la syntaxe, sous licence dans son intégralité sous Creative Commons. L’annotation syntaxique contient deux niveaux: un niveau macro-syntactique, contenant une segmentation en unités illocutionnaires (y compris des marqueurs de discours, des parenthèses...) et un niveau micro-syntactique comprenant des relations de dépendance et diverses structures paradigmatiques, appelées constructions de pile, ces dernières étant particulièrement fréquentes et diversifiées dans le langage parlé. Le processus d’annotation micro-syntactique, présenté dans cet article, comprend une préparation semi-automatique de la transcription, l’application d’un analyseur de dépendance syntaxique, le transcodage des résultats d’analyse au schéma d’annotation Rhapsodie, la correction manuelle par plusieurs annotateurs suivie d’un processus de validation, et enfin l’application de règles de cohérence qui vérifient les erreurs courantes. Les bons scores d’accord inter-annotateurs sont présentés et analysés plus en détail. L’article comprend également la liste des fonctions utilisées dans l’annotation de dépendance et pour la distinction des différentes constructions de pieux et présente les idées qui sous-tendent ces choix."""

In [6]:
text18234 = """Modèle sémantique basé sur BERT pour le recalage de la N meilleure liste de reconnaissance de la parole

Ce travail vise à améliorer la reconnaissance automatique de la parole (ASR) en modélisant les relations sémantiques à long terme. Nous proposons d'y parvenir en recalant la liste des N meilleures hypothèses de la reconnaissance automatique de la parole. Pour ce faire, nous proposons deux modèles de réseaux neuronaux profonds (DNN) et combinons des informations sémantiques, acoustiques et linguistiques. Nos modèles de recalage DNN visent à sélectionner des hypothèses qui ont une meilleure cohérence sémantique et donc un WER plus faible. Nous étudions une représentation puissante dans le cadre des caractéristiques d'entrée de notre modèle DNN : les enchâssements contextuels dynamiques du BERT basé sur les transformateurs. Des caractéristiques acoustiques et linguistiques sont également incluses. Nous réalisons des expériences sur l'ensemble de données publiques TED-LIUM. Nous évaluons dans des conditions propres et bruyantes, avec des n-grammes et un modèle linguistique de réseau neuronal récurrent (RNNLM), plus précisément un modèle de mémoire à long terme (LSTM). Les approches de rescoring proposées apportent des améliorations significatives du WER par rapport au système ASR sans modèle de rescoring. En outre, la combinaison des méthodes de recadrage basées sur les scores BERT et GPT-2 donne les meilleurs résultats."""

In [29]:
mt = [[18608, text18608], [935, text935], [2433, text2433], [18234, text18234]]

import pandas as pd

mt_df = pd.DataFrame(mt, columns=["translation_id", "translation"])

In [30]:
mt_df.iloc[0]['translation']

"Exploration de la structure des catégories à l'aide de modèles linguistiques contextuels et de réseaux sémantiques lexicaux\n\nDes travaux récents sur la prédiction de la structure des catégories avec des modèles distributionnels, utilisant soit des enchâssements de mots statiques (Heyman et Heyman, 2019), soit des modèles de langage contextualisés (CLM) (Misra et al., 2021), font état de faibles corrélations avec les évaluations humaines, remettant ainsi en question leur plausibilité en tant que modèles de la mémoire sémantique humaine. Dans ce travail, nous revisitons cette question en testant un plus large éventail de méthodes pour sonder les CLMs afin de prédire les scores de typicalité. Nos expériences, utilisant BERT (Devlin et al., 2018), montrent l'importance d'utiliser le bon type de sondes CLM, car nos meilleures méthodes de prédiction de typicalité basées sur BERT s'améliorent considérablement par rapport aux travaux précédents. Deuxièmement, nos résultats soulignent l'importance de la polysémie dans cette tâche : nos meilleurs résultats sont obtenus lors de l'utilisation d'un mécanisme de désambiguïsation. Enfin, des expériences supplémentaires révèlent que le WordNet basé sur le contenu de l'information (Miller, 1995), également doté d'un mécanisme de désambiguïsation, atteint les mêmes performances que la meilleure méthode basée sur l'ERTB et capture en fait des informations complémentaires, qui peuvent être combinées avec l'ERTB pour améliorer les prédictions de typicalité."

In [31]:
mt_df.head()

   translation_id                                        translation
0           18608  Exploration de la structure des catégories à l...
1             935  Efficacité des modèles de langue française sur...
2            2433  Correction et validation de la dépendance synt...
3           18234  Modèle sémantique basé sur BERT pour le recala...

###

### tokenize the pe from exp1 translator set using xcomet's tokenizer

In [22]:
# load the tokenizer
tokenizer = model.encoder.tokenizer


def tokenize_with_offsets(text):
    """Tokenize text and return (words, offsets)"""
    tokenized = tokenizer(
        text,
        return_offsets_mapping=True,
        return_tensors="pt",
        truncation=True
    )
    
    word_ids = tokenized.word_ids()
    offset_mapping = tokenized["offset_mapping"][0].tolist()
    
    word_to_data = {}
    for idx, (word_id, (start, end)) in enumerate(zip(word_ids, offset_mapping)):
        if word_id is None:
            continue
        if word_id not in word_to_data:
            word_to_data[word_id] = {
                "tokens": [],
                "start": start+1 if word_id > 0 else start,
                "end": end
            }
        else:
            word_to_data[word_id]["end"] = end
        token = tokenizer.convert_ids_to_tokens(tokenized["input_ids"][0][idx].item())
        word_to_data[word_id]["tokens"].append(token)
    
    word_mapping = []
    word_offsets = []
    for word_id in sorted(word_to_data.keys()):
        data = word_to_data[word_id]
        word = tokenizer.convert_tokens_to_string(data["tokens"]).strip()
        word_mapping.append(word)
        word_offsets.append((data["start"], data["end"]))
    
    return word_mapping, word_offsets

# Process DataFrame
def process_row(row):
    # Process translation
    pe_text = row["text"][0] if isinstance(row["text"], list) else row["text"]
    pe_tokens, pe_offsets = tokenize_with_offsets(pe_text)
    
    
    return pd.Series({
        "pe_tokenized": pe_tokens,
        "pe_word_offset": pe_offsets,
    })

# Apply to DataFrame
new_cols = df.apply(process_row, axis=1)
df = pd.concat([df, new_cols], axis=1)

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

In [23]:
df.head()

,id,user_id,translation_id,annotator_id,text,pe_tokenized,pe_word_offset
0,4004,502,18608,1,Exploration de la structure catégorielle à l'a...,"[Exploration, de, la, structure, catégorielle,...","[(0, 11), (12, 14), (15, 17), (18, 27), (28, 4..."
1,4005,502,2433,1,Correction et validation des dépendances synta...,"[Correction, et, validation, des, dépendances,...","[(0, 10), (11, 13), (14, 24), (25, 28), (29, 4..."
2,4006,502,935,1,Efficacité des modèles de langue du français s...,"[Efficacité, des, modèles, de, langue, du, fra...","[(0, 10), (11, 14), (15, 22), (23, 25), (26, 3..."
3,4007,502,18234,1,Modèle sémantique basé sur BERT pour le rescor...,"[Modèle, sémantique, basé, sur, BERT, pour, le...","[(0, 6), (7, 17), (18, 22), (23, 26), (27, 31)..."
4,4008,503,2433,1,Correction et validation des dépendances synta...,"[Correction, et, validation, des, dépendances,...","[(0, 10), (11, 13), (14, 24), (25, 28), (29, 4..."

In [24]:
pe_18608 = df.iloc[0]['text']

In [27]:
pe_18608[12:14]

'de'

### tokenize the mt from exp1 translator set using xcomet's tokenizer

In [32]:
# load the tokenizer
tokenizer = model.encoder.tokenizer


def tokenize_with_offsets(text):
    """Tokenize text and return (words, offsets)"""
    tokenized = tokenizer(
        text,
        return_offsets_mapping=True,
        return_tensors="pt",
        truncation=True
    )
    
    word_ids = tokenized.word_ids()
    offset_mapping = tokenized["offset_mapping"][0].tolist()
    
    word_to_data = {}
    for idx, (word_id, (start, end)) in enumerate(zip(word_ids, offset_mapping)):
        if word_id is None:
            continue
        if word_id not in word_to_data:
            word_to_data[word_id] = {
                "tokens": [],
                "start": start+1 if word_id > 0 else start,
                "end": end
            }
        else:
            word_to_data[word_id]["end"] = end
        token = tokenizer.convert_ids_to_tokens(tokenized["input_ids"][0][idx].item())
        word_to_data[word_id]["tokens"].append(token)
    
    word_mapping = []
    word_offsets = []
    for word_id in sorted(word_to_data.keys()):
        data = word_to_data[word_id]
        word = tokenizer.convert_tokens_to_string(data["tokens"]).strip()
        word_mapping.append(word)
        word_offsets.append((data["start"], data["end"]))
    
    return word_mapping, word_offsets

# Process DataFrame
def process_row(row):
    # Process translation
    mt_text = row["translation"][0] if isinstance(row["translation"], list) else row["translation"]
    mt_tokens, mt_offsets = tokenize_with_offsets(mt_text)
    
    
    return pd.Series({
        "mt_tokenized": mt_tokens,
        "mt_word_offset": mt_offsets,
    })

# Apply to DataFrame
new_cols = mt_df.apply(process_row, axis=1)
mt_df = pd.concat([mt_df, new_cols], axis=1)

In [33]:
mt_df

,translation_id,translation,mt_tokenized,mt_word_offset
0,18608,Exploration de la structure des catégories à l...,"[Exploration, de, la, structure, des, catégori...","[(0, 11), (12, 14), (15, 17), (18, 27), (28, 3..."
1,935,Efficacité des modèles de langue française sur...,"[Efficacité, des, modèles, de, langue, françai...","[(0, 10), (11, 14), (15, 22), (23, 25), (26, 3..."
2,2433,Correction et validation de la dépendance synt...,"[Correction, et, validation, de, la, dépendanc...","[(0, 10), (11, 13), (14, 24), (25, 27), (28, 3..."
3,18234,Modèle sémantique basé sur BERT pour le recala...,"[Modèle, sémantique, basé, sur, BERT, pour, le...","[(0, 6), (7, 17), (18, 22), (23, 26), (27, 31)..."

### use difflib to get the changes in the pedited of the mt

In [34]:
# from difflib import SequenceMatcher

# para1 = "This is a simple sentence for testing."
# para2 = "This is a slightly different sentence used for testing."

# words1 = para1.split()
# words2 = para2.split()

# matcher = SequenceMatcher(None, words1, words2)
# opcodes = matcher.get_opcodes()

# for tag, i1, i2, j1, j2 in opcodes:
#     print(f"{tag:7} words1[{i1}:{i2}] -> {words1[i1:i2]} | words2[{j1}:{j2}] -> {words2[j1:j2]}")

equal   words1[0:3] -> ['This', 'is', 'a'] | words2[0:3] -> ['This', 'is', 'a']
replace words1[3:4] -> ['simple'] | words2[3:5] -> ['slightly', 'different']
equal   words1[4:5] -> ['sentence'] | words2[5:6] -> ['sentence']
insert  words1[5:5] -> [] | words2[6:7] -> ['used']
equal   words1[5:7] -> ['for', 'testing.'] | words2[7:9] -> ['for', 'testing.']

In [39]:
def get_difflib_result(mt_words, pe_words):

    matcher = SequenceMatcher(None, mt_words, pe_words)
    opcodes = matcher.get_opcodes()
    
    return opcodes

In [40]:
opcodes = get_difflib_result(mt_df.iloc[0]["mt_tokenized"], df.iloc[0]["pe_tokenized"])

In [42]:
mt_words = mt_df.iloc[0]["mt_tokenized"]
pe_words = df.iloc[0]["pe_tokenized"]

In [43]:
for tag, i1, i2, j1, j2 in opcodes:
        print(f"{tag:7} mt_words[{i1}:{i2}] -> {mt_words[i1:i2]} | pe_words[{j1}:{j2}] -> {pe_words[j1:j2]}")

equal   mt_words[0:4] -> ['Exploration', 'de', 'la', 'structure'] | pe_words[0:4] -> ['Exploration', 'de', 'la', 'structure']
replace mt_words[4:6] -> ['des', 'catégories'] | pe_words[4:5] -> ['catégorielle']
equal   mt_words[6:10] -> ['à', "l'aide", 'de', 'modèles'] | pe_words[5:9] -> ['à', "l'aide", 'de', 'modèles']
replace mt_words[10:11] -> ['linguistiques'] | pe_words[9:11] -> ['de', 'langues']
equal   mt_words[11:26] -> ['contextuels', 'et', 'de', 'réseaux', 'sémantiques', 'lexicaux', 'Des', 'travaux', 'récents', 'sur', 'la', 'prédiction', 'de', 'la', 'structure'] | pe_words[11:26] -> ['contextuels', 'et', 'de', 'réseaux', 'sémantiques', 'lexicaux', 'Des', 'travaux', 'récents', 'sur', 'la', 'prédiction', 'de', 'la', 'structure']
replace mt_words[26:30] -> ['des', 'catégories', 'avec', 'des'] | pe_words[26:30] -> ['catégorielle', 'à', "l'aide", 'de']
equal   mt_words[30:35] -> ['modèles', 'distributionnels,', 'utilisant', 'soit', 'des'] | pe_words[30:35] -> ['modèles', 'distributionnels,', 'utilisant', 'soit', 'des']
replace mt_words[35:38] -> ['enchâssements', 'de', 'mots'] | pe_words[35:37] -> ['plongements', 'lexicaux']
equal   mt_words[38:47] -> ['statiques', '(Heyman', 'et', 'Heyman,', '2019),', 'soit', 'des', 'modèles', 'de'] | pe_words[37:46] -> ['statiques', '(Heyman', 'et', 'Heyman,', '2019),', 'soit', 'des', 'modèles', 'de']
replace mt_words[47:48] -> ['langage'] | pe_words[46:47] -> ['langue']
equal   mt_words[48:52] -> ['contextualisés', '(CLM)', '(Misra', 'et'] | pe_words[47:51] -> ['contextualisés', '(CLM)', '(Misra', 'et']
replace mt_words[52:53] -> ['al.,'] | pe_words[51:52] -> ['coll.,']
equal   mt_words[53:82] -> ['2021),', 'font', 'état', 'de', 'faibles', 'corrélations', 'avec', 'les', 'évaluations', 'humaines,', 'remettant', 'ainsi', 'en', 'question', 'leur', 'plausibilité', 'en', 'tant', 'que', 'modèles', 'de', 'la', 'mémoire', 'sémantique', 'humaine.', 'Dans', 'ce', 'travail,', 'nous'] | pe_words[52:81] -> ['2021),', 'font', 'état', 'de', 'faibles', 'corrélations', 'avec', 'les', 'évaluations', 'humaines,', 'remettant', 'ainsi', 'en', 'question', 'leur', 'plausibilité', 'en', 'tant', 'que', 'modèles', 'de', 'la', 'mémoire', 'sémantique', 'humaine.', 'Dans', 'ce', 'travail,', 'nous']
replace mt_words[82:83] -> ['revisitons'] | pe_words[81:84] -> ['étudions', 'à', 'nouveau']
equal   mt_words[83:86] -> ['cette', 'question', 'en'] | pe_words[84:87] -> ['cette', 'question', 'en']
replace mt_words[86:88] -> ['testant', 'un'] | pe_words[87:91] -> ['expérimentant', 'à', "l'aide", "d'un"]
equal   mt_words[88:96] -> ['plus', 'large', 'éventail', 'de', 'méthodes', 'pour', 'sonder', 'les'] | pe_words[91:99] -> ['plus', 'large', 'éventail', 'de', 'méthodes', 'pour', 'sonder', 'les']
replace mt_words[96:97] -> ['CLMs'] | pe_words[99:100] -> ['CLM']
equal   mt_words[97:100] -> ['afin', 'de', 'prédire'] | pe_words[100:103] -> ['afin', 'de', 'prédire']
replace mt_words[100:101] -> ['les'] | pe_words[103:104] -> ['des']
equal   mt_words[101:110] -> ['scores', 'de', 'typicalité.', 'Nos', 'expériences,', 'utilisant', 'BERT', '(Devlin', 'et'] | pe_words[104:113] -> ['scores', 'de', 'typicalité.', 'Nos', 'expériences,', 'utilisant', 'BERT', '(Devlin', 'et']
replace mt_words[110:111] -> ['al.,'] | pe_words[113:114] -> ['coll.,']
equal   mt_words[111:120] -> ['2018),', 'montrent', "l'importance", "d'utiliser", 'le', 'bon', 'type', 'de', 'sondes'] | pe_words[114:123] -> ['2018),', 'montrent', "l'importance", "d'utiliser", 'le', 'bon', 'type', 'de', 'sondes']
insert  mt_words[120:120] -> [] | pe_words[123:125] -> ['sur', 'le']
equal   mt_words[120:121] -> ['CLM,'] | pe_words[125:126] -> ['CLM,']
replace mt_words[121:122] -> ['car'] | pe_words[126:132] -> ['comme', 'en', 'témoigne', 'le', 'fait', 'que']
equal   mt_words[122:132] -> ['nos', 'meilleures', 'méthodes', 'de', 'prédiction', 'de', 'typicalité', 'basées', 'sur', 'BERT'] | pe_words[132:142] -> ['nos', 'meilleures', 'méthodes', 'de', 'prédiction', 'de', 'typicalité', 'basées', 'sur', 'BERT']
replace mt_words[132:133] -> ["s'améliorent"] | pe_words[142:143] -> ['surpassent']
equal   mt_words[133:134] -> ['considérablement'] | pe_words[143:144] -> ['considérablement']
replace mt_words[134:137] -> ['par', 'rapport', 'aux'] | pe_words[144:145] -> ['les']
equal   mt_words[137:175] -> ['travaux', 'précédents.', 'Deuxièmement,', 'nos', 'résultats', 'soulignent', "l'importance", 'de', 'la', 'polysémie', 'dans', 'cette', 'tâche', ':', 'nos', 'meilleurs', 'résultats', 'sont', 'obtenus', 'lors', 'de', "l'utilisation", "d'un", 'mécanisme', 'de', 'désambiguïsation.', 'Enfin,', 'des', 'expériences', 'supplémentaires', 'révèlent', 'que', 'le', 'WordNet', 'basé', 'sur', 'le', 'contenu'] | pe_words[145:183] -> ['travaux', 'précédents.', 'Deuxièmement,', 'nos', 'résultats', 'soulignent', "l'importance", 'de', 'la', 'polysémie', 'dans', 'cette', 'tâche', ':', 'nos', 'meilleurs', 'résultats', 'sont', 'obtenus', 'lors', 'de', "l'utilisation", "d'un", 'mécanisme', 'de', 'désambiguïsation.', 'Enfin,', 'des', 'expériences', 'supplémentaires', 'révèlent', 'que', 'le', 'WordNet', 'basé', 'sur', 'le', 'contenu']
replace mt_words[175:178] -> ['de', "l'information", '(Miller,'] | pe_words[183:189] -> ['en', 'information', '(Information', 'Content-based', 'WordNet;', 'Miller,']
equal   mt_words[178:195] -> ['1995),', 'également', 'doté', "d'un", 'mécanisme', 'de', 'désambiguïsation,', 'atteint', 'les', 'mêmes', 'performances', 'que', 'la', 'meilleure', 'méthode', 'basée', 'sur'] | pe_words[189:206] -> ['1995),', 'également', 'doté', "d'un", 'mécanisme', 'de', 'désambiguïsation,', 'atteint', 'les', 'mêmes', 'performances', 'que', 'la', 'meilleure', 'méthode', 'basée', 'sur']
replace mt_words[195:196] -> ["l'ERTB"] | pe_words[206:207] -> ['BERT']
equal   mt_words[196:208] -> ['et', 'capture', 'en', 'fait', 'des', 'informations', 'complémentaires,', 'qui', 'peuvent', 'être', 'combinées', 'avec'] | pe_words[207:219] -> ['et', 'capture', 'en', 'fait', 'des', 'informations', 'complémentaires,', 'qui', 'peuvent', 'être', 'combinées', 'avec']
replace mt_words[208:209] -> ["l'ERTB"] | pe_words[219:220] -> ['BERT']
equal   mt_words[209:215] -> ['pour', 'améliorer', 'les', 'prédictions', 'de', 'typicalité.'] | pe_words[220:226] -> ['pour', 'améliorer', 'les', 'prédictions', 'de', 'typicalité.']