In [1]:
!pwd

/auto/brno2/brno2/rahmang/xcomet/arafat_comet/COMET_GR/eng_to_czech

In [3]:
home = "/auto/brno2/brno2/rahmang/"

In [4]:
import os

In [5]:
abstract_metadata = "thesis_czech/thesis_codes/abstract_metadata_with_ideal_spans_correct_no_spans_with_min4chars.tsv"

In [6]:
path = os.path.join(home,abstract_metadata)

In [8]:
import pandas as pd

df = pd.read_csv(path, sep="\t")

print(df.head())

    hal_id  translation_id                                   sentence_indices  \
0  3911658           18797  [1749, 1750, 1751, 1752, 1753, 1754, 1755, 175...
1  3946223           10147  [152, 153, 154, 155, 156, 157, 158, 159, 160, ...
2  3602177           17469  [1858, 1859, 1860, 1861, 1862, 1863, 1864, 186...
3  3636034           11525  [1191, 1192, 1193, 1194, 1195, 1196, 1197, 119...
4  3972415           12792  [1537, 1538, 1539, 1540, 1541, 1542, 1543, 154...

   num_sentences  total_characters  \
0             20              3318
1             26              3308
2             16              3162
3             15              2892
4             13              2845

                                              source  total_spans  \
0  An intermestic approach to China's public dipl...            8
1  Development of a holistic communication score ...            7
2  Improving reusability along the data life cycl...            4
3  Cross-Situational Learning Towards Robot Groun...           14
4  Zero-Shot Style Transfer for Gesture Animation...           21

   total_span_chars  span_char_ratio_pct
0               106                 3.19
1                97                 2.93
2               154                 4.87
3               216                 7.47
4               287                10.09

In [1]:
# read the df_en_cz_original_with_id_numbers df
import pandas as pd

df = pd.read_csv("./df_en_cz_original_with_id_numbers")

In [2]:
df.head()

,ref,systems,src,id_hal,Translation_id,line_id
0,{'R1': 'Vláda přikázala odchod do důchodu dalš...,{'CUNI-DocTransformer.1450': {'score': 0.76862...,The government has compulsorily retired 15 mor...,1,1,1
1,{'R1': 'Ústřední rada nepřímých daní a cel (CB...,{'CUNI-DocTransformer.1450': {'score': 0.58643...,The Central Board of Indirect Taxes and Custom...,1,1,2
2,"{'R1': 'Od června je to už počtvrté, co jsou z...",{'CUNI-DocTransformer.1450': {'score': 0.63602...,"Since June, this is the fourth round of sackin...",1,1,3
3,{'R1': 'Podle oficiálních zdrojů proběhla akce...,{'CUNI-DocTransformer.1450': {'score': -0.2728...,Sources said the action was in line with Prime...,1,1,4
4,"{'R1': '„Nedávno jsme podnikli odvážný krok, k...",{'CUNI-DocTransformer.1450': {'score': 0.37188...,"""We have recently taken the bold step of compu...",1,1,5

In [3]:
df_en_cz = pd.read_csv("df_en_cz_final.csv")
df_en_cz.head(16)

,id_hal,Translation_id,line_id,source,translation,postedition
0,1,1,1,The government has compulsorily retired 15 mor...,Vláda povinně odešla do důchodu dalších 15 daň...,Vláda přikázala odchod do důchodu dalším 15 da...
1,1,1,2,The Central Board of Indirect Taxes and Custom...,Ústřední rada nepřímých daní a cel (CBIC) - ag...,Ústřední rada nepřímých daní a cel (CBIC) – ag...
2,1,1,3,"Since June, this is the fourth round of sackin...",Od června je to čtvrté kolo vyhození zkorumpov...,"Od června je to už počtvrté, co jsou zkorumpov..."
3,1,1,4,Sources said the action was in line with Prime...,"Zdroj uvedl, že akce byla v souladu s adresou ...",Podle oficiálních zdrojů proběhla akce v návaz...
4,1,1,5,"""We have recently taken the bold step of compu...","""Nedávno jsme podnikli odvážný krok povinného ...","„Nedávno jsme podnikli odvážný krok, když jsme..."
5,1,1,6,Nearly half of the officials retired were thos...,"Téměř polovina úředníků v důchodu byli ti, kte...","Téměř polovina úředníků, kteří odešli do důcho..."
6,1,1,7,"In June, the government had compulsorily retir...",V červnu vláda povinně odešla do důchodu 15 úř...,V červnu vláda donutila odejít do důchodu 15 ú...
7,1,1,8,"In August, the government compulsorily retired...",V srpnu vláda povinně odešla do důchodu 22 úře...,V srpnu vláda poslala do důchodu 22 úředníků C...
8,2,2,1,A woman in Maine got 500 letters from United H...,Žena v Maine dostala 500 dopisů od United Heal...,Žena v Maine obdržela během pěti dnů 500 dopis...
9,2,2,2,Stephanie Lay said she found the piles of lett...,"Stephanie Lay uvedla, že ve čtvrtek a pondělí ...","Stephanie Layová uvedla, že během čtvrtka a po..."
10,2,2,3,"""A week ago Thursday was the first wave of let...","„Před týdnem byla čtvrtek první vlna dopisů, m...",„Před týdnem ve čtvrtek přišla první vlna dopi...
11,2,2,4,"And the letters just kept coming, piling up to...",A dopisy právě přicházely a v pondělí se hroma...,Dopisy chodily dál a v pondělí se jich nahroma...
12,2,2,5,"They were addressed to her son, who has autism...","Byli adresováni svému synovi, který má autismu...","Byly adresovány jejímu synovi, který trpí auti..."
13,2,2,6,The letters were about a $54 or $0 healthcare ...,Dopisy se týkaly zdravotního tvrzení ve výši 5...,Dopisy se týkaly nároku na zdravotní péči ve v...
14,2,2,7,When she asked United Healthcare why she was r...,"Když se zeptala na United Healthcare, proč dos...","Když se zeptala United Healthcare, proč dostáv..."
15,2,2,8,"In a statement, United Healthcare told CNN it'...","United Healthcare v prohlášení uvedla, že CNN ...",Společnost United Healthcare v prohlášení pro ...

In [1]:
import pandas as pd

df_en_cz = pd.read_csv("./df_en_cz_final_with_selected_8_docs.csv")
df_en_cz.head(10)

,id_hal,Translation_id,line_id,source,translation,postedition
0,3,3,1,Using data and artificial intelligence to try ...,Využití dat a umělé inteligence k vyzkoušení a...,Využití dat a umělé inteligence ke zvýšení výn...
1,3,3,2,"""It's one of the first commercial uses of inve...",„Je to jedno z prvních komerčních investic do ...,„Je to jedna z prvních komerčních investic do ...
2,3,3,3,HSBC declined to comment on how much it expect...,"HSBC se odmítla vyjádřit k tomu, co očekává od...","HSBC se odmítla vyjádřit k tomu, co očekává od..."
3,3,3,4,The drive is an important part of the bank's e...,Pohon je důležitou součástí úsilí banky bránit...,Kampaň je důležitou součástí úsilí banky obháj...
4,3,3,5,HSBC was forced to invest hundreds of millions...,HSBC byla nucena investovat stovky milionů dol...,HSBC byla nucena investovat stovky milionů dol...
5,3,3,6,The system works by mapping individual custome...,"Systém funguje tak, že mapuje jednotlivé zákaz...","Systém funguje tak, že mapuje jednotlivé zákaz..."
6,3,3,7,That system has already freed up more than 400...,Tento systém již uvolnil více než 400 zaměstna...,Tento systém umožnil již více než 400 zaměstna...
7,3,3,8,HSBC's Nivison said the lightbulb moment was r...,"Společnost Nivison společnosti HSBC uvedla, že...","Pan Nivison z HSBC řekl, že si banka náhle uvě..."
8,5,5,1,Stem cells of 56 child cancer patients lost at...,Kmenové buňky 56 pacientů s rakovinou u dětí z...,Kmenové buňky 56 dětských pacientů s rakovinou...
9,5,5,2,A freezer malfunction at Children's Hospital L...,Porucha mrazáku v dětské nemocnici v Los Angel...,Porucha mrazáku v dětské nemocnici v Los Angel...

In [2]:
import json
path_spans_ideal = "./spans_ideal_df_en_cz_final_with_selected_8_docs.json"
with open(path_spans_ideal, 'r', encoding='utf-8') as f:
    spans_ideal = json.load(f)

In [4]:
spans_ideal[0]

[{'text': ['k', 'vyzkoušení', 'a'], 'start': 31, 'end': 46},
 {'text': ['HSBC'], 'start': 87, 'end': 92},
 {'text': ['vytlačení'], 'start': 95, 'end': 105},
 {'text': ['z', 'jeho'], 'start': 110, 'end': 117},
 {'text': ['klíčová', 'priorita'], 'start': 165, 'end': 182}]

In [5]:
len(spans_ideal)

64

In [6]:
spans_ideal[0]

[{'text': ['k', 'vyzkoušení', 'a'], 'start': 31, 'end': 46},
 {'text': ['HSBC'], 'start': 87, 'end': 92},
 {'text': ['vytlačení'], 'start': 95, 'end': 105},
 {'text': ['z', 'jeho'], 'start': 110, 'end': 117},
 {'text': ['klíčová', 'priorita'], 'start': 165, 'end': 182}]

In [7]:
# ideal spans with relevant words

with open("spans_ideal_df_en_cz_final_with_selected_8_docs_with_relevant_words.json", 'r', encoding='utf-8') as f:
    spans_ideal_with_relevant_words = json.load(f)
    
spans_ideal_with_relevant_words[0]

[{'text': ['k', 'vyzkoušení', 'a'], 'start': 31, 'end': 46},
 {'text': ['HSBC'], 'start': 87, 'end': 92},
 {'text': ['vytlačení'], 'start': 95, 'end': 105},
 {'text': ['z', 'jeho'], 'start': 110, 'end': 117},
 {'text': ['klíčová', 'priorita'], 'start': 165, 'end': 182},
 ['k',
  'vyzkoušení',
  'a',
  'HSBC',
  'vytlačení',
  'z',
  'jeho',
  'klíčová',
  'priorita']]